# Generated by Django 3.2.4 on 2023-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happytales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrais',
            name='user',
        ),
        migrations.AddField(
            model_name='fundrais',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fundrais',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
